#!/bin/bash

. /usr/share/git/completion/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUPSTREAM="auto"

cd "$(tmux showenv "$(tmux display -p "TMUX_PWD_#D")" | cut -d= -f2-)"

[[ -d $PWD/.git ]] || exit
S_BG=colour234

if [[ -f $PWD/.git/MERGE_HEAD ]]; then
    FG='#000000'
    BG='#fcf946'
    printf "#[fg=$S_BG,bg=$BG]⮀#[fg=$FG,bg=colour$BG,bold] ⌥  #[fg=$BG,bg=$FG]⮀"
fi

if [[ -d $PWD/.git/rebase-merge || -d $PWD/.git/rebase-apply ]]; then
    FG='#000000'
    BG='#fcf946'
    printf "#[fg=$S_BG,bg=$BG]⮀#[fg=$FG,bg=colour$BG,bold] rebase #[fg=$BG,bg=$FG]⮀"
fi

printf '#[fg=colour235,bg=colour252]⮀#[fg=colour235,bg=colour252]  %s ' $(git rev-parse --abbrev-ref HEAD)
